### ISSUE TITLE
corrosion_link_libraries doesn't seem to handle multiple libraries

### ISSUE THREAD

**Issue by housel** [corrosion-rs/corrosion#128]
While `corrosion_link_libraries` seems to work with a single library, when there is more than one then:

- `${link_libs}` and `${search_dirs}` get expanded in the custom command as unquoted, space-separated values, which breaks the setting of the corresponding environment variables
- After adding quotes to fix the above, it still doesn't work because `corrosion_build::build_script();` is expecting a semicolon-separated list.

I'm using CMake 3.22.

**Comment by jschwe** [comment]
Thanks for the report! 

> After adding quotes to fix the above, it still doesn't work because corrosion_build::build_script(); is expecting a semicolon-separated list.

Yeah, that is wrong - opened a PR with a fix.
