### ISSUE TITLE
rust-lib-requiring-envvar test fails on cmake 3.22.2

### ISSUE THREAD

**Issue by housel** [corrosion-rs/corrosion#134]
On Ubuntu 20.04LTS, after building CMake 3.22.2 from the tag, running

    git clone https://github.com/corrosion-rs/corrosion.git
    cd corrosion/test
    cmake -G Ninja .
    ninja

fails with:

       Compiling rust-lib-requiring-envvar v0.1.0 (/tmp/corrosion/test/envvar) error: environment variable `REQUIRED_VARIABLE` not defined
     --> build.rs:2:16
      |
    2 |     assert_eq!(env!("REQUIRED_VARIABLE"), "EXPECTED_VALUE");
      |                ^^^^^^^^^^^^^^^^^^^^^^^^^
      |
      = note: this error originates in the macro `env` (in Nightly builds, run with -Z macro-backtrace for more info)

    error: could not compile `rust-lib-requiring-envvar` due to previous error

As noted elsewhere, I traced this problem to commit 93ae1fe. It still fails with `CORROSION_EXPERIMENTAL_PARSER=OFF`.

**Comment by jschwe** [comment]
Thanks for the report! The issue should be fixed on master now. Can you confirm that?

**Comment by housel** [comment]
Yes, I can confirm it works now, thanks!
