### ISSUE TITLE
Could not find Rust_CARGO_CACHED using the following names: cargo

### ISSUE THREAD

**Issue by kvark** [corrosion-rs/corrosion#145]
Just trying this out on a project in NixOS.
My cmake:
```
add_subdirectory(mod/corrosion)
find_package(Corrosion REQUIRED)
```
Output:
```
$ cmake ..
CMake Error at mod/corrosion/cmake/FindRust.cmake:186 (find_program):
  Could not find Rust_CARGO_CACHED using the following names: cargo
Call Stack (most recent call first):
  mod/corrosion/cmake/Corrosion.cmake:22 (find_package)
  mod/corrosion/CMakeLists.txt:63 (include)
```
I see that cargo executable is looked up in `HINTS "${_RUST_TOOLCHAIN_PATH}/bin"`. On my system, cargo isn't placed anywhere near Rust:
```
$ which rustc
/nix/store/sqw563f9ggjjkzlrf37h6fvqiz40hwpj-rustc-1.57.0/bin/rustc

$ which cargo
/nix/store/5q06j36iqzymwsgskq3p7lidl8bfkjxv-cargo-1.57.0/bin/cargo
```

**Comment by jschwe** [comment]
That's definitely an interesting case. I'm not familiar with nixos, but you can specify the paths to rustc and cargo manually:

Just set `Rust_COMPILER` and `Rust_CARGO` to the correct paths before calling `find_package(Corrosion)`. Or if you are using corrosion as a subdirectory before the `add_subdirectory`. 

Documented in the [advanced](https://github.com/corrosion-rs/corrosion#advanced) section.

**Comment by kvark** [comment]
Thank you for the answer! It's somewhat unfortunate to specify them manually, given that they are already in `PATH`.

**Comment by jonringer** [comment]
It would probably be good to fall back to a `find_program` to find cargo. The canonical POSIX way to find an application is through PATH.
