### ISSUE TITLE
Support #[no_std] crates

### ISSUE THREAD

**Issue by arkkors** [corrosion-rs/corrosion#153]
Currently, when trying to add `no-std`-crates, several libraries are linked to the resulting binaries, causing several linking issues.
A way to disable this behavior would be great

**Comment by jschwe** [comment]
I definitely support this. I think it should be sufficient to add a flag to the generator that disables adding [this rustflag](https://github.com/corrosion-rs/corrosion/blob/904fefbedff0a781ea6db861100f584326adb19c/generator/src/subcommands/build_crate.rs#L127). If for some reason you want `no_std` on Windows/Linux/Mac, then you would also have to add an option to disable linking of [the libraries added here](https://github.com/corrosion-rs/corrosion/blob/master/generator/src/subcommands/gen_cmake/platform.rs).

I'm currenlty pretty busy so I don't have the time to do this myself, but it should be pretty simple to do even for a new contributor. So if you or someone else has the time, I would be happy to accept a PR.

**Comment by arkkors** [comment]
You got a MR which seems to be doing what it is supposed to do :)
