### ISSUE TITLE
Change required checks from windows-latest to windows-2019

### ISSUE THREAD

**Issue by jschwe** [corrosion-rs/corrosion#155]
The original CI checks for windows-latest don't work anymore since windows-latest now points to windows-2022. This can't be fixed, since the minimum supported CMake version for the updated VS in windows-2022 is 3.21 (I think).
So for now we should just remove the required checks in the repository settings or switch them to 2019.

@ogoffart I think you have the rights to do this change, so I assigned you.

**Comment by ogoffart** [comment]
I *think* this is done now.
I also ave you admin right, so you can do it yourself in the future.

**Comment by jschwe** [comment]
Thanks!
