### ISSUE TITLE
corrosion_link_libraries doesn't respect the OUTPUT_NAME property

### ISSUE THREAD

**Issue by ADKaster** [corrosion-rs/corrosion#172]
I was trying to link a rust crate to c++ libraries that were defined in my project, and came across the todo in corrosion_link_libraries

```cmake
        # TODO: The output name of the library can be overridden - find a way to support that.
        corrosion_add_target_rustflags(${target_name} "-l${library}")
```

This is exactly my problem, my libraries are defined as `add_library(LibFoo SHARED ${some_sources})` and then the actual filename on the filesystem is set like `set_target_properties(LibFoo PROPERTIES OUTPUT_NAME foo)`

I found that swapping out the actual link line with
```cmake
        if (TARGET ${library})
            corrosion_add_target_rustflags(${target_name} "-l$<TARGET_PROPERTY:${library},OUTPUT_NAME>")
        else()
            corrosion_add_target_rustflags(${target_name} "-l${library}")
        endif()
```

seems to do the trick, even if it's a bit ugly.

Would a patch like this be accepted as-is? What kind of testing would you want to confirm it works in more situations than the current code?

**Comment by ogoffart** [comment]
This looks sensible. Please make a pull request.

As for the test, you can maybe simply add a test that tries to compile a library with a different output name.  (or change one of the existing test to specify the output name (maybe in the test/workspace))

**Comment by ADKaster** [comment]
Hmm. looking at the rest of the link libraries helper, I don't think the TARGET check is required. the TARGET_LINKER_FILE_DIR part already falls over if ${library_name} is not already a target. e.g. if you wanted to explicitly link against libgcc.a for whatever reason.  Makes the change much simpler.
