### ISSUE TITLE
_add_cargo_build warnings when using from-source rust build

### ISSUE THREAD

**Issue by ADKaster** [corrosion-rs/corrosion#174]
I'm building rustc and cargo from source in my repository rather than using a rustup'd or otherwise installed stable/nightly version.

My locally built toolchain is found via setting Rust_ROOT and Rust_CARGO_TARGET before doing ``FetchContent_MakeAvailable(Corrosion)``

For each crate I include in my build, I get spammed with 
```
CMake Warning at build/_deps/corrosion-src/cmake/Corrosion.cmake:323 (message):
  Regex didnt match on .  If you are using a custom toolchain consider
  renaming your toolchain to contain only lowercase letters, or open an
  issue.
```

If I set(Rust_TOOLCHAIN) to some random semver the warnings go away, but that feels hackish...

What I can't figure out is what this check is actually supposed to do?

https://github.com/corrosion-rs/corrosion/blob/46944de3ae562acc7eef277185ad356dae88f09f/cmake/Corrosion.cmake#L317-L325

That rust_toolchain_override variable is never referenced anywhere else in the project, at least not on current master.

**Comment by ogoffart** [comment]
Right, this doesn't seem to be used.

 @jschwe   should this simply be removed?

**Comment by jschwe** [comment]
Yes, this can be removed - actually it should not have even been added in the first place. This `if` is part of a workaround, which I figured out how to avoid before merging commit 27dbf8d.
