### ISSUE TITLE
How to omit warning “No linker preference for target native”?

### ISSUE THREAD

**Issue by dbsxdbsx** [corrosion-rs/corrosion#176]
I am trying to use `corrosion` to bind rust with flutter, with [frb](https://github.com/fzyzcjy/flutter_rust_bridge/issues/425). I've installed `corrosion`. And everything goes fine, but I don't know what does this warning mean:
```
CMake Warning at C:/Program Files (x86)/Corrosion/share/cmake/Corrosion.cmake:314 (message):
  No linker preference for target native
Call Stack (most recent call first):
  C:/Program Files (x86)/Corrosion/share/cmake/CorrosionGenerator.cmake:329 (_add_cargo_build)
  C:/Program Files (x86)/Corrosion/share/cmake/CorrosionGenerator.cmake:479 (_generator_add_target)
  C:/Program Files (x86)/Corrosion/share/cmake/Corrosion.cmake:408 (_generator_add_cargo_targets)
  rust.cmake:15 (corrosion_import_crate)
  CMakeLists.txt:53 (include)
```
And how to solve it?

**Comment by jschwe** [comment]
It basically means that corrosion does not know which linker it should specify for the rust target called "native", which results in cargo picking one itself, which may or may not work as expected.

So I guess your usecase is that you build your "native" target via CMake and corrosion and then somehow link it to flutter, so you do not enable any language in CMake at all, right? Do you care about which linker is used in your usecase, or is the one cargo will pick fine for you?

**Comment by jschwe** [comment]
It basically means that corrosion does not know which linker it should specify for the rust target called "native", which results in cargo picking one itself, which may or may not work as expected.

So I guess your usecase is that you build your "native" target via CMake and corrosion and then somehow link it to flutter, so you do not enable any language in CMake at all, right? Do you care about which linker is used in your usecase, or is the one cargo will pick fine for you?

**Comment by dbsxdbsx** [comment]
> It basically means that corrosion does not know which linker it should specify for the rust target called "native", which results in cargo picking one itself, which may or may not work as expected.
> 
> So I guess your usecase is that you build your "native" target via CMake and corrosion and then somehow link it to flutter, so you do not enable any language in CMake at all, right? Do you care about which linker is used in your usecase, or is the one cargo will pick fine for you?

The result is fine, just this warning is little annoying. But I am afraid that  it would become a  hidden trouble. How to fix it? Do I have to rename "native" to some meaningful text?

**Comment by jschwe** [comment]
> Do I have to rename "native" to some meaningful text?

No, the name of your crate is not related to this in any way.

It seems like you are linking your Rust code into C++ and not the other way around, so I guess the warning is not necessary in your case. I'd have to give some thought on how to detect when the warning is not necessary.

Since you do have CXX enabled as a language, I'm a bit curious why you are getting the warning at all. Could you check if `CMAKE_CXX_LINKER_PREFERENCE` is set by CMake ?

**Comment by dbsxdbsx** [comment]
> > Do I have to rename "native" to some meaningful text?
> 
> No, the name of your crate is not related to this in any way.
> 
> It seems like you are linking your Rust code into C++ and not the other way around, so I guess the warning is not necessary in your case. I'd have to give some thought on how to detect when the warning is not necessary.
> 
> Since you do have CXX enabled as a language, I'm a bit curious why you are getting the warning at all. Could you check if `CMAKE_CXX_LINKER_PREFERENCE` is set by CMake ?

I am trying to build a windows app for win10, with rust as backend and flutter/dart as ui. Currently, the best way to link these 2 is through FFI, but only c-like interface could be adopted by dart side. To avoid boil plate code, a template called [flutter-rust-bridge](https://github.com/fzyzcjy/flutter_rust_bridge) is found. Simply, the template just[ translate rust code by generated rust code to c/cpp code,then generate some code to communicate with dart](http://cjycode.com/flutter_rust_bridge/template/generate_install.html). And `corrosion` is used in the c/cpp part with cmake.

I've made my own [template](https://github.com/dbsxdbsx/testFrb) compilable. But the warning made I post this issue.
For question ` why you are getting the warning at all`, frankly, I don't know either. Maybe the file under `./windows` is helpful.

And for your suggestion `CMAKE_CXX_LINKER_PREFERENCE`, I found little info for this property. I've tried to paste `SET(CMAKE_CXX_LINKER_PREFERENCE 30)` to both `windows\CMakeLists.txt` and `windows\rust.cmake`, but this warning still exists.

**Comment by jschwe** [comment]
Probably in your case the issue is that you don't select any specific C++ compiler (which is okay), so CMake doesn't have a preferred linker for C++. I'm leaning towards downgrading the warning to a status message, since it's not really possible for us to reliably detect when a warning would really be appropriate.
