### ISSUE TITLE
Allow for offline builds

### ISSUE THREAD

**Issue by jonringer** [corrosion-rs/corrosion#191]
The current corrosion workflow resolves the manifest by pinging a remote endpoint to resolve the dependencies using the Cargo.toml. However, this workflow doesn't work well if there's no network connectivity.

## Context

Many package managers (e.g. debian, ubuntu, rpm, nix) will perform the builds in isolated sandboxes. This ensures that the packages have all of their dependencies captured and increases reproducibility ([why that matters](https://reproducible-builds.org/)).

### Other tooling available during build

A Cargo.lock is also available, which seems to overlap with the manifest step.

Using `cargo vendor`, there is a pre-resolved local cache of dependencies available, but I haven't found a way to tell corrosion about it. Seems like work for resolving the manifest is to later populate a different cache in the build directory, it would be nice to have a way to configure

**Comment by jschwe** [comment]
This should be possible via `cargo vendor`. The required configuration should be written to a [`.cargo/config.toml`](https://doc.rust-lang.org/cargo/reference/config.html).
The  `.cargo/config.toml` must be located in a parent of the CMake *build* directory to be found by cargo (Corrosion invokes the `cargo build` command in a subdirectory  of `CMAKE_BINARY_DIR`), so placing the file in the source directory may not work depending on the project structure.

Corrosion does currently generate a `config.toml` in the build directory itself, but it shouldn't contain any conflicting keys (regarding vendoring), so as long as your `config.toml` is in a parent directory, the unification done by cargo should work and allow vendoring to be used.

**Comment by jschwe** [comment]
Closing - I believe this should already be possible. If there is some issue I'd need a minimal example of what exactly fails when using vendored dependencies.
