### ISSUE TITLE
Interoperation with `cbindgen`

### ISSUE THREAD

**Issue by mladedav** [corrosion-rs/corrosion#195]
I haven't found anything regarding using header files generated from `cbindgen` for shared libraries written in Rust.

I think it might be a nice addition from the point of view of someone like me who has very little experience with CMake.

Would it be ok if I made a PR with a working solution I've come up with and we can iterate on that since I'm sure I've broken some best practices?

**Comment by jschwe** [comment]
Sure, I'd definitely appreciate that!
