### ISSUE TITLE
`PROFILE dev` does not work

### ISSUE THREAD

**Issue by mladedav** [corrosion-rs/corrosion#198]
`dev` is the default so this isn't that bad but still. Specifying `PROFILE dev` in `corrosion_import_crate` leads to the following error for me:

Windows:
```
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(242,5): error MSB8066: Custom build for 'C:\corrosion\test\build\CMakeFiles\c553a666e3d9aab2aeff55446b3148a1\cargo-build_rust-lib.rule' exited with code 1. [C:\corrosion\test\build\rust2cpp\cargo-build_rust-lib.vcxproj]
```

WSL:
```
Error copying file (if different) from "/mnt/c/corrosion/test/wsl/./cargo/build/x86_64-unknown-linux-gnu/dev/librust_lib.a" to "/mnt/c/corrosion/test/wsl/rust2cpp".
make[3]: *** [rust2cpp/CMakeFiles/cargo-build_rust-lib.dir/build.make:72: rust2cpp/CMakeFiles/cargo-build_rust-lib] Error 1
make[2]: *** [CMakeFiles/Makefile2:482: rust2cpp/CMakeFiles/cargo-build_rust-lib.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:541: rust2cpp/CMakeFiles/cpp-exe.dir/rule] Error 2
make: *** [Makefile:228: cpp-exe] Error
```

In both cases the compilation is successful. Omitting or specifying different profile (such as `release`) makes it work.

This is from the `rust2cpp` example in this project but it happens in my other projects too.

**Comment by jschwe** [comment]
Thanks for the report. I guess we will have to add a special case for the "dev" profile, since unfortunately the output directory name is not the same as the profile name but "debug" instead.

**Comment by mladedav** [comment]
Oh, I could have figured that one out. In that case, there are also exceptions for `test` (also in `debug`) and `bench` (in `release`). People probably wouldn't use these directly but I assume better safe than sorry.

**Comment by jschwe** [comment]
The `dev` profile is fixed. We can't really do anything about test or bench because cargo also appends a hash to the artifact names for those profiles, so we just don't support those two profiles.
