### ISSUE TITLE
Reusing artifacts in `target` from previous (CMake non-related) build

### ISSUE THREAD

**Issue by mladedav** [corrosion-rs/corrosion#199]
I am building my crate in CI and if that succeeds I build it again with CMake. I think there should be a way to skip this additional compilation by reusing the artifacts in the `target` directory.

This can probably be solved fairly easily once `--out-dir` is stabilized ([context](https://github.com/rust-lang/cargo/issues/6100); this may not be stabilized ever) by allowing the user to specify a preexisting target directory while keeping just the output local to cmake.

But until then I'm not so sure. I know simply moving the target directory anywhere wouldn't work since there are absolute paths there based on which recompilation is triggered. I tried to test it and it triggered the compilation but honestly I'm still a bit confused sometimes when cargo decides to rebuild.

**Comment by jschwe** [comment]
Have you considered using "sccache" to cache your compilation results?

**Comment by jschwe** [comment]
Closing in favor of issue https://github.com/corrosion-rs/corrosion/issues/328, which would also address this issue.
