### ISSUE TITLE
Trying to use Corrosion in CMake build results in CMake error Failed to parse "Default host"

### ISSUE THREAD

**Issue by lawli3t** [corrosion-rs/corrosion#200]
I am currently trying to integrate Corrosion with an existing CPP project (https://github.com/ElektraInitiative/libelektra)

I am currently using a Debian sid docker Container with the newest `rust-all` package available installed (rustc 1.59.0, cargo 1.56.0).

When trying to build a simple example application I encounter the following error:

```
CMake Error at /usr/local/share/cmake/FindRust.cmake:136 (message):
  Failed to parse "Default host" from `/cargo/bin/rustup show`.  Got:
Call Stack (most recent call first):
  /usr/local/share/cmake/Corrosion.cmake:41 (find_package)
  /usr/local/lib/cmake/Corrosion/CorrosionConfig.cmake:42 (include)
  src/libs/rust/CMakeLists.txt:3 (find_package)
```

I have tried setting Variables that set the path for the rust toolchain manually like so:

```
set(Rust_ROOT /usr/bin)
```

but it is still trying to use the path `/cargo/bin`, it doesn't seem to make ANY difference. Am I specifying this wrong? I have also tried other variables similarly (`Rust_TOOLCHAIN`, `Rust_COMPILER`, `Rust_CARGO`) but Corrosion doesn't seem to honor any settings at all.  I don't get where this is coming from since I never set any `CARGO_HOME` envvar or similar to `/cargo`. It is always trying to use the `/cargo/bin/rustup` binary, I can't seem to be able to convince Corrosion to use the packaged version of cargo. Is there any possibility I can force Corrosion to use the pre-packaged Rust version?

The envvars in the docker container are as follows:

```
jenkins@f2f49882c42a:~/workspace/elektra-build-docker$ env
HOSTNAME=f2f49882c42a
LANGUAGE=C.UTF-8
PWD=/home/jenkins/workspace/elektra-build-docker
HOME=/home/jenkins
LANG=C.UTF-8
LS_COLORS=[...]
SHFMT_PATH=/home/jenkins/bin
TERM=xterm
SHLVL=1
GTEST_ROOT=/opt/gtest
SHFMT_VERSION=v3.3.1
LC_ALL=C.UTF-8
PATH=/home/jenkins/bin:/usr/lib/llvm-13/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/gradle/bin:/home/jenkins/.local/share/gem/ruby/3.0.0/bin
_=/usr/bin/env
OLDPWD=/home/jenkins/workspace
```

The respective CMake file: 

```
cmake_minimum_required(VERSION 3.12)

find_package(Corrosion REQUIRED)

corrosion_import_crate(MANIFEST_PATH libc/Cargo.toml)

add_executable(rust-libc-test libc/examples/basic/main.c)
target_link_libraries(rust-libc-test elektra-rs-libc
```

Sadly, it is impossible for me to use any newer version of CMake.

I installed Corrosion in the Dockerfile like so:

```
RUN mkdir /home/jenkins/corrosion
WORKDIR /home/jenkins/corrosion
RUN git clone https://github.com/corrosion-rs/corrosion.git
RUN sed -i '1 i cargo-features = ["named-profiles"]' /home/jenkins/corrosion/corrosion/test/custom_profiles/rust/Cargo.toml
RUN mkdir /home/jenkins/.cargo
RUN echo '[unstable]\nunstable-options = true' > /home/jenkins/.cargo/config.toml
RUN cmake -Scorrosion -Bbuild -DCMAKE_BUILD_TYPE=Release
RUN cmake --build build --config Release
USER root
RUN cmake --install build --config Release
RUN rm -rf /home/jenkins/corrosion
USER ${JENKINS_USERID}
```

**Comment by lawli3t** [comment]
Ok, I'm an idiot - the Debian package doesn't provide rustup which would of course explain my whole issue. I tried before manually installing rust via rustup but encountered other problems. I will be trying this route again and hopefully find a solution to my issue.

**Comment by jschwe** [comment]
If you need to use CMake 3.12, you should stick with the v0.2.x tags of corrosion. 
`FindRust` currently works fine with CMake 3.12 even on master, but for corrossion we currently require CMake 3.15 on master (May even be increased before the next release).

Regarding your original issue:
> CMake Error at /usr/local/share/cmake/FindRust.cmake:136 (message):
  Failed to parse "Default host" from `/cargo/bin/rustup show`.  Got:

Corrosion should work even if you don't have rustup installed. But the block of code where the error happens should only be executed if rustup is installed.
I would think everything should work just fine if  `Rust_TOOLCHAIN` and all other variables are NOT set. Could you clean the CMake cache and try again?

**Comment by lawli3t** [comment]
> If you need to use CMake 3.12, you should stick with the v0.2.x tags of corrosion. `FindRust` currently works fine with CMake 3.12 even on master, but for corrossion we currently require CMake 3.15 on master (May even be increased before the next release).
> 
> Regarding your original issue:
> 
> > CMake Error at /usr/local/share/cmake/FindRust.cmake:136 (message):
> > Failed to parse "Default host" from `/cargo/bin/rustup show`.  Got:
> 
> Corrosion should work even if you don't have rustup installed. But the block of code where the error happens should only be executed if rustup is installed. I would think everything should work just fine if `Rust_TOOLCHAIN` and all other variables are NOT set. Could you clean the CMake cache and try again?

This worked like a charm, thank you so much! Saved me a lot of time on my masters thesis.
