### ISSUE TITLE
Specify compile target in one crate

### ISSUE THREAD

**Issue by 21pages** [corrosion-rs/corrosion#201]
There is several compile target in one crate, such as
```
[package]
name = "hello"
edition = "2021"
build= "build.rs"
default-run = "test"

[lib]
name = "libhello"
crate-type = ["cdylib", "staticlib", "rlib"]

[[bin]]
name = "naming"
path = "src/naming.rs"
```

```
corrosion_import_crate(MANIFEST_PATH ../../Cargo.toml)
target_link_libraries(${BINARY_NAME} PRIVATE libhello)
```

I just need to compile `libhello`, but now it compiles `libhello`, `hello`, `naming`. 

Is there a way to  compile `libhello` only? May the option can added for enhancement.

**Comment by jschwe** [comment]
> Is there a way to compile libhello only? May the option can added for enhancement.

Currently this is not possible - but it may be possible in the future.

**Comment by 21pages** [comment]
thanks, looking forward to it.

**Comment by jschwe** [comment]
On current master (after https://github.com/corrosion-rs/corrosion/pull/216) if you build a target that only links `libhello`, then `naming` should not be built anymore. Please note that `naming` however still is built when the `ALL` target is built. 

If this does not work as expected for you, please feel free to reopen the issue.
