### ISSUE TITLE
Failure to compile, "undefined reference to `rust_second_function'"

### ISSUE THREAD

**Issue by PureTryOut** [corrosion-rs/corrosion#202]
I'm trying to compile corrosion 0.2.1 but it's failing for me and I don't really understand why.

```
ninja: job failed: : && /usr/lib/ccache/bin/g++ -Os -fomit-frame-pointer -Os -DNDEBUG -Wl,--as-needed test/rustflags/CMakeFiles/rustflags-cpp-exe.dir/main.cpp.o -o test/rustflags/rustflags-cpp-exe  test/rustflags/librustflag_test_lib.a  -ldl  -lrt  -lpthread  -lgcc_s  -lc  -lm  -lutil && :
/usr/lib/gcc/x86_64-alpine-linux-musl/12.1.1/../../../../x86_64-alpine-linux-musl/bin/ld: test/rustflags/CMakeFiles/rustflags-cpp-exe.dir/main.cpp.o: in function `main':
main.cpp:(.text.startup+0x1c): undefined reference to `rust_second_function'
collect2: error: ld returned 1 exit status
```

**Comment by jschwe** [comment]
This is one of our tests that is failing.

Could you share your CMake and Rust version as well as how you configured corrosion?

**Comment by PureTryOut** [comment]
The Rust version is 1.63.0, CMake is 3.24.1.

The CMake call I'm doing:

```
cmake -B build -G Ninja \
    -DCMAKE_BUILD_TYPE=MinSizeRel \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DBUILD_SHARED_LIBS=True
```

**Comment by jschwe** [comment]
Ah, that test doesn't work as expected when used with `MinSizeRel`. I'll fix the test, but in the meantime you can add a `-DCORROSION_BUILD_TESTS=OFF` when configuring to disable building the tests.

Thanks for the report!

**Comment by PureTryOut** [comment]
I'll rather wait for the test to be fixed than disabling them :wink: I'll be patient!

**Comment by jschwe** [comment]
I published a new version containing the fix.
