### ISSUE TITLE
OUTPUT_DIRECTORY and linking against a corrosion-produced library

### ISSUE THREAD

**Issue by mnutt** [corrosion-rs/corrosion#240]
I was using corrosion (a fairly [recent version](https://github.com/corrosion-rs/corrosion/commit/bff871054636297221c82ccb5647399b2ce4258b)) in a subproject to build a thin wrapper around the oxipng API, and was then trying to dynamically link my main c++ project against it. I was trying to do it this way vs statically linking because my main app and test executables are pretty small, whereas oxipng is pretty large. I set `LIBRARY_OUTPUT_DIRECTORY` to `${CMAKE_BINARY_DIR}/lib` which caused the library to be put in the correct place but produced the `make` error `No rule to make target 'vendor/oxipng/oxipng_encoder.dylib', needed by 'app'. Stop.` (despite the dylib now being in `lib/`)

I created a minimal replication here: https://github.com/corrosion-rs/corrosion/compare/master...mnutt:corrosion:output-directory-linking

which just creates a `consumer` executable and links the corrosion-produced library. It produces the error:

```
[ 50%] Building CXX object CMakeFiles/consumer.dir/consumer.cpp.o
gmake[2]: *** No rule to make target 'librust_lib.a', needed by 'consumer'.  Stop.
gmake[1]: *** [CMakeFiles/Makefile2:374: CMakeFiles/consumer.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
CMake Error at ./corrosion/test/ConfigureAndBuild.cmake:103 (message):
  Build step failed.  Exit code: `2`
```

I tried with ninja just to see what would happen and got a very similar error. I observed it on both mac/clang and linux/gcc. Apologies if I'm just using it incorrectly or if what I'm trying to do shouldn't be possible, but I'm guessing the dependency resolution step is somehow happening prior to the output_directory move? FWIW the workaround I eventually used was to statically link the corrosion-produced target against an intermediate `SHARED` target (along with some `-force_load`/`--whole-archive` stuff) and link _that_ to my main app, which worked ok.

**Comment by jschwe** [comment]
Thanks for reporting this and providing a test case!

It looks like the code responsible for setting `IMPORTED_LOCATION` needs to be tweaked. It needs to set the imported location for the `<target_name>-static` and `-shared` CMake targets, but as a side effect also looks for the `OUTPUT_DIRECTORY` properties on these targets instead of the main `target_name` target.
