### ISSUE TITLE
Blocking issues before releasing v0.3

### ISSUE THREAD

**Issue by jschwe** [corrosion-rs/corrosion#246]
- [x] Add section about OUTPUT_DIRECTORY to the Readme.  
- [x] Document that `IMPORTED_LOCATION` will be set late (important if e.g. the users writes these properties to some configuration file like slint does). Should be added to the Breaking section in the Changelog.
- [ ] Set `soname` for cdylibs. See [here](https://github.com/rust-lang/cargo/issues/5045#issuecomment-1255613521) and [here](https://gitlab.kitware.com/cmake/cmake/-/issues/22307#note_971562). Maybe also just set IMPORTED_NO_SONAME

potentially more...

**Comment by Be-ing** [comment]
CXX-Qt is working with the 0.3 beta: https://github.com/KDAB/cxx-qt/pull/340
