### ISSUE TITLE
Linking issue for internal `-static` target in cxx integration

### ISSUE THREAD

**Issue by niyue** [corrosion-rs/corrosion#262]
Suppose I have a C++ library `my_lib` that depends on the `my_cxx_bridge_target`, which uses the `corrision_add_cxxbridge` function to generate. 

If I try to use `my_lib` in another program `my_app`, during linking `my_app`, linker (ld under macOS 12) will report error like:
```
ld: library not found for -lmy_cxx_bridge_target-static
```

Here `my_cxx_bridge_target` is the target I specified when calling `corrision_add_cxxbridge` function, and it seems `my_cxx_bridge_target-static` is an internal target introduced by corrosion within this function, and this `my_cxx_bridge_target-static` target is marked as `INTERFACE_LINK_LIBRARIES` for the `my_cxx_bridge_target`.

I think it is this line
https://github.com/corrosion-rs/corrosion/blob/b921fd09155c05255a6b0df6d9901f919ce81b6b/cmake/Corrosion.cmake#L605

So when linking against `my_cxx_bridge_target`, the `my_cxx_bridge_target-static` will be linked. However, this target may require export/install to be linked.

I am not completely sure what the best approach for addressing this issue, do you think if this should be addressed in corrosion or if this should be done in corrosion users' side? If it should be done by corrosion users, what could be the recommended way to do it? Thanks.

**Comment by jschwe** [comment]
Could you provide a small example project that reproduces the error? You could e.g. start with the [rust2cpp test file](https://github.com/corrosion-rs/corrosion/blob/master/test/rust2cpp/rust2cpp/CMakeLists.txt)

**Comment by niyue** [comment]
Okay, my project uses vcpkg and is more complex than necessary to reproduce the error. Let me see if I can come up with a minimum example for reproducing it. I will probably off for a few days, and will get back to you later. Thanks.

**Comment by jschwe** [comment]
Friendly ping - does this issue still occur?

**Comment by niyue** [comment]
Sorry for the delay, I gave it a try previously but ran into an irrelevant issue in my project. I will close this issue and may re-open it if I manage to get a chance to revisit it. Thanks.
