### ISSUE TITLE
Faliure to find targets after upgrading to 0.3.0

### ISSUE THREAD

**Issue by Vaporeon** [corrosion-rs/corrosion#266]
After upgrading 0.2.2 to 0.3.0, it no longer works and I am not sure why.

```
CMake Error at /usr/share/cmake/CorrosionGenerator.cmake:203 (message):
  found no targets in 11 packages
Call Stack (most recent call first):
  /usr/share/cmake/Corrosion.cmake:1111 (_generator_add_cargo_targets)
  dependencies.cmake:25 (corrosion_import_crate)
  CMakeLists.txt:23 (include)
```

Even more strangely it fails when downgrading back to 0.2.2, even though the same code worked before????

**Comment by jschwe** [comment]
It seems you are using an installed version of Corrosion with CMake >= 3.19. Could you check if you face the same issues when using corrosion as a submodule instead of as an installed package? Also it may be informative to run the configure stage with [--log-level=Debug](https://cmake.org/cmake/help/latest/manual/cmake.1.html#cmdoption-cmake-log-level)

**Comment by Vaporeon** [comment]
I'm using CMake 3.24.3. `--log-level=Debug` was helpful, thanks for mentioning that.

```
-- Rust Toolchain: stable-x86_64-unknown-linux-gnu
-- Rust toolchain stable-x86_64-unknown-linux-gnu
-- Rust toolchain path /home/sam/.rustup/toolchains/stable-x86_64-unknown-linux-gnu
-- Rust Target: x86_64-unknown-linux-gnu
-- Cargo target x86_64-unknown-linux-gnu is an official target-triple
-- Installed targets: x86_64-pc-windows-gnu;x86_64-unknown-linux-gnu
-- Using Corrosion as a subdirectory
-- Parsed Target triple: arch: x86_64, vendor: unknown, OS: linux, env: gnu
-- Found 1 targets in package rat-in-a-tube
-- No relevant targets found in package rat-in-a-tube - Ignoring
```

I get the same result if using `FetchContent`

So, it seems Cargo.toml has to have a [lib] section with the crate type, or else nothing will be found.

**Comment by Vaporeon** [comment]
For reference I am using this crate [here](https://github.com/SnowyMouse/riat).

Previously you could use `corrosion_import_crate(MANIFEST_PATH riat/Cargo.toml)` and then link `riatc` directly, but that no longer works.

**Comment by jschwe** [comment]
> Previously you could use corrosion_import_crate(MANIFEST_PATH riat/Cargo.toml) and then link riatc directly, but that no longer works.

That would surprise me. `riat` is just a rust library (produces only a `.rlib` artifact) with no `staticlib` or `cdylib` targets. Corrosion previously should have also just done nothing at all. The only thing that was added was exiting with a fatal error in case `corrosion_import_crate` was called and no suitable targets where found. The previous behaviour would have just been "silently do nothing".

Is it possible that there where other changes, e.g. converting the Cargo.toml from a workspace to a package toml? In that case corrosion may have just been picking up `riatc` directly if it was a workspace member.

**Comment by Vaporeon** [comment]
Ohhh, I see.
I see the commits that did indeed chance it from a workspace to a package, so that is why it worked before.
Thanks for explaining things.
