### ISSUE TITLE
Using custom target json file is breaking artefacts copying ?

### ISSUE THREAD

**Issue by mean00** [corrosion-rs/corrosion#315]
Hi, i'm running into an issue and could use some pointers
The gist of it is that i'm using a non standard target (riscv32imacf-unknown-none-elf). It is slightly different from the non float version but enough so it will not link if both are mixed.

As a result the target is different, i.e. instead of 
 SET(Rust_CARGO_TARGET "riscv32imacf-unknown-none-elf" )
it is 
 SET(Rust_CARGO_TARGET "${SOME_PATH}/riscv32imacf-unknown-none-elf.json" )

Where the json file is describing the target.

That works fine up to the copy by_product step where it is using TARGET to contruct the path to the source artefact(s) to copy 
So, when a json target file is used, it will insert the full path of the json file in the "source" path  & fail.

I can try to provide a patch but could use some guidance.

Thank you

**Comment by jschwe** [comment]
Thanks for the report. I think #316 should be sufficient to fix this, but it would be great if you could verify this.
