### ISSUE TITLE
add option to link with WHOLE_ARCHIVE for staticlibs

### ISSUE THREAD

**Issue by Be-ing** [corrosion-rs/corrosion#320]
CMake provides a [generator expression feature](https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html?highlight=whole_archive#genex:LINK_LIBRARY) to tell the linker to link all symbols in a static archive rather than searching the archive for used symbols (as detailed in [GNU ld's documentation](https://sourceware.org/binutils/docs/ld/Options.html#index-including-an-entire-archive)). This is required to avoid the linker throwing away static variables which need to be initialized before `main` but the symbols aren't referenced from within `main`.

Qt makes use of such static variables for a few purposes including initializing [static Qt plugins](https://doc.qt.io/qt-5/plugins-howto.html#details-of-linking-static-plugins), which are used for custom QML elements, and initializing [embedded resources](https://doc.qt.io/qt-6/resources.html#explicit-loading-and-unloading-of-embedded-resources). In cxx-qt-build, generated C++ code which has such static variables gets compiled by the Rust build script and linked into the Rust staticlib with the [`+whole-archive` option for rustc](https://doc.rust-lang.org/rustc/command-line-arguments.html#linking-modifiers-whole-archive). When the combined Rust and C++ staticlib gets linked into C++ code by Corrosion, the `$<LINK_LIBRARY:WHOLE_ARCHIVE,library_name>` generator expression needs to be used to avoid the linker throwing away those static variables again. In most situations, this option would cause bloated binaries for no reason, so it should be opt-in, not the default. I suggest to add a `WHOLE_ARCHIVE` option to `corrosion_import_crate`.

**Comment by jschwe** [comment]
I don't see why corrosion needs to do anything here. The user just uses CMake as usual, and adds the genex if they need it.

```cmake
target_link_libraries(cpp_lib PRIVATE "$<LINK_LIBRARY:WHOLE_ARCHIVE,rust_static_lib>")
```
