### ISSUE TITLE
GLIBC minimum version requirements

### ISSUE THREAD

**Issue by rbdm-qnt** [corrosion-rs/corrosion#366]
I'm trying to use Corrosion on a server which has Ubuntu 20 installed, and I can't upgrade it to Ubuntu 22 due to other requirements, so the maximum GLIBC version I can install is the 2.31. When trying to compile corrosion I'm getting this error:

../corrosion/cxxbridge_v1.0.92/bin/cxxbridge: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ../corrosion/cxxbridge_v1.0.92/bin/cxxbridge)
../corrosion/cxxbridge_v1.0.92/bin/cxxbridge: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ../corrosion/cxxbridge_v1.0.92/bin/cxxbridge)
../corrosion/cxxbridge_v1.0.92/bin/cxxbridge: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ../corrosion/cxxbridge_v1.0.92/bin/cxxbridge)

What can I do about this? I thought maybe this could be an unnecessary requirement, or I could use an older version of the lib, and if so which one would be best?

**Comment by jschwe** [comment]
Did you build on the same machine?

**Comment by temeddix** [comment]
I'm having an exact same issue:
```
...
e84b97b375d4/build_script_build-f992e84b97b375d4" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-nodefaultlibs"
  = note: /snap/flutter/current/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/liblto_plugin.so: error loading plugin: /snap/flutter/141/usr/bin/../../lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/lib/gcc/x86_64-linux-gnu/11/liblto_plugin.so)
          collect2: error: ld returned 1 exit status


error: could not compile `camino` (build script) due to previous error
...
```
This appears as soon as I add `corrosion_import_crate` to my CMAKE file.

**Comment by temeddix** [comment]
Now I got to know that this was the problem of the Flutter provided by `snap` on Ubuntu.
https://stackoverflow.com/a/74290508
I followed the instructions on this answer, which was downloading the `deb` Flutter, and it is now solved :)
