### ISSUE TITLE
Provide a nicer error when no packages are found

### ISSUE THREAD

**Issue by OlivierLDff** [corrosion-rs/corrosion#380]
It would be nice to provide a better error for a user that might have failed to match CRATES name with the one actually in Cargo.toml
https://github.com/corrosion-rs/corrosion/blob/4c36abff079364d6ebdf51526fc3457c216a0545/cmake/CorrosionGenerator.cmake#L278.

What do you think about if `CRATES` is set by user, variant message listing all packages that have been found?
Something like `Fail to find your-crate,other-crate in N packages (package1,package2) etc...`.

Idea is coming from this user report that had error unrelated to cxx-qt: https://github.com/KDAB/cxx-qt/issues/516

**Comment by jschwe** [comment]
We do already print some helpful information if you set the CMake log level to at least `DEBUG`:  https://github.com/corrosion-rs/corrosion/blob/4c36abff079364d6ebdf51526fc3457c216a0545/cmake/CorrosionGenerator.cmake#L234.

Perhaps we could suggest the user to reconfigure with `cmake --log-level=DEBUG` if they encounter this error. Printing all the packages like you suggested is also possible, but the crate names don't need to match the package names, so it could also be confusing the user.

**Comment by OlivierLDff** [comment]
I've never used the debug feature really nice to hear that it exists! I will try to use it in my next projects
