### ISSUE TITLE
Projects with multiple Rust targets have broken incremental compilation

### ISSUE THREAD

**Issue by 2xsaiko** [corrosion-rs/corrosion#386]
After updating Corrosion from 0.3.0 to 0.3.5, I noticed every time I build my whole project, it rebuilds all Rust crates including dependencies, instead of building the project incrementally as before. When building the same Rust target twice, the second time does not cause a rebuild (as expected). When building one Rust target, then another, then the first one again, all three times all dependencies are rebuilt from scratch. This makes me think that building a target causes incremental builds to get invalidated for all the other targets.

I tracked it down to commit 798fc952a7753fa8d592bc9f7e37bfe0fe4898fd (introduced between 0.3.1 and 0.3.2), reverting the commit [in my project](https://git.dblsaiko.net/nucom/commit/?h=idl&id=3d3bbcdc63d85c2695179295ef6017fa3277a1d8) fixes the issue.

**Comment by jschwe** [comment]
Have you also tried if this still happens on current master? I just checked, and the code in question, which did not set `CARGO_TARGET_<target>_LINKER` for `staticlib`s, is not there anymore on master (after a larger refactor).

I am considering releasing a bugfix release, which reverts the commit in question, but I'd have to take some time first and doublecheck what the original issue was, to make sure I don't break something else by reverting.

**Comment by 2xsaiko** [comment]
Ah sorry, I forgot to test master. It does indeed not happen there anymore. Thanks!

**Comment by jschwe** [comment]
Do you need a fix for the v0.3 branch, or would releasing v0.4 be sufficient?

**Comment by 2xsaiko** [comment]
Having the fix in 0.4 is fine by me. Applying a patch until then is not an issue :)
