### ISSUE TITLE
Multi configuration builds don't work

### ISSUE THREAD

**Issue by xTachyon** [corrosion-rs/corrosion#399]
My CMake knowledge is quite limited, so I'm sorry if I misjudged anything here.

When using a build with multiple configurations set, like this:
```
cmake .. -DCMAKE_CONFIGURATION_TYPES=Debug;Release
```
[This](https://github.com/corrosion-rs/corrosion/blob/master/cmake/Corrosion.cmake#L296) line using the `output_dir` var seems to be breaking the build. From what I could test, it looks like `output_dir` var is empty after the generator expr is evaluated, which results in the command `cmake -E make_directory` to be called without a string, which triggers the help message for that command and a failed build.

It seems weird for me that stuff like `<CONFIG:debug>` is not triggered at all when it comes with multi config builds; I don't know what other variant could be used.

Am I doing something wrong or is this just not working?

**Comment by jschwe** [comment]
Are you using a multi config Generator? E.g. Ninja Multiconfig?

**Comment by jschwe** [comment]
I've opened https://github.com/corrosion-rs/corrosion/pull/400 to give users a helpful warning if they have misconfigured CMake by setting `CMAKE_CONFIGURATION_TYPES`, even though the generator they are using is single-config.
