### ISSUE TITLE
Multi-crate setup: Recompiling shared dependencies

### ISSUE THREAD

**Issue by riidefi** [corrosion-rs/corrosion#424]
I am noticing that in a multi-crate setup, my CI time is largely spent on recompiling the same common dependencies. Is there any existing feature I could use to either cache cargo deps across CI runs, or share them between crates?

I do not know if this is feasible and I understand it is not a pressing issue. Thank you for your wonderful project--it's beyond useful as-is.

**Comment by OlivierLDff** [comment]
have you tried [sccache](https://github.com/mozilla/sccache)?

**Comment by jschwe** [comment]
If the crates share a workspace and you don't set different RUSTFLAGS for different crates, the shared dependencies should only be compiled once.

**Comment by jschwe** [comment]
@riidefi Could you provide some more details?

**Comment by riidefi** [comment]
Closing. You are absolutely correct. I did not realize that each library version was an entirely distinct build target. Apologies for any confusion and I hope I did not waste your time much at all. I am genuinely sorry for not checking that--I'm not sure how I looked over something so obvious.

That being said, The sscache suggestion was helpful given the deps don't change run-to-run.
