### ISSUE TITLE
Way to install a package from crates.io?

### ISSUE THREAD

**Issue by riidefi** [corrosion-rs/corrosion#449]
I was wondering what the most idiomatic way to install a package from crates.io would be? My initial thought would be to use `FetchContent` and then pass the path to `corrosion_import_crate`, but this approach might be messy in the case that multiple rust crates belong to the same git repository (for instance, one project I have).

Ideally, I would like something that mirrors Rust's `Cargo.toml` files, like here:
```toml
[dependencies]
libc = "0.2"
```
maybe a `corrosion_import_public_crate(CRATE_NAME "libc" VERSION "0.2")`?
While this is probably not in the cards for this repository, is there any direction you could offer here? Perhaps I am missing a simple way to tackle this problem?

(This is only really relevant for crates that provide an external C API, for instance [my gctex library](https://github.com/riidefi/RiiStudio/tree/master/source/gctex). Rust installation is trivial (via crates.io); inter-project C++ installation is trivial; broader C++ installation would not be so simple, though.)

**Comment by riidefi** [comment]
Looks like the following would work
```cmake
include(FetchContent)
FetchContent_Declare(
  gctex
  URL      https://crates.io/api/v1/crates/gctex/0.1.0/download
  URL_HASH MD5=9AE87143B95F209416E0C08B0939406D
)
FetchContent_MakeAvailable(gctex)
corrosion_import_crate(MANIFEST_PATH ${gctex_SOURCE_DIR}/Cargo.toml CRATE_TYPES staticlib FLAGS --crate-type=staticlib)
```

**Comment by jschwe** [comment]
This is not really related to corrosion, but more generally to adding subprojects in CMake. You could take a look at CPM which wraps FetchContent: https://github.com/cpm-cmake/CPM.cmake#cpm_source_cache

**Comment by notable-equivalent** [comment]
To help with the convenience of this, a fairly simple shell function can quickly get you the URL and hash of a crate from crates.io:

```bash
get-rust-crate-url-and-hash() {
    if [ "$#" -ne 2 ]; then
        echo "Usage: get-rust-crate-url-and-hash CRATE_NAME CRATE_VERSION" >&2
        return 1
    fi

    CRATE_NAME="$1"
    CRATE_VERSION="$2"

    CRATE_INFO_URL="https://crates.io/api/v1/crates/${CRATE_NAME}/${CRATE_VERSION}"

    CRATE_CHECKSUM="$(curl -A 'get-rust-crate-url-and-hash' -s "$CRATE_INFO_URL" | python3 -c 'import json, sys; print(json.load(sys.stdin)["version"]["checksum"])')"

    cat << EOF
FetchContent_Declare(
    ${CRATE_NAME}
    URL "${CRATE_INFO_URL}/download"
    URL_HASH SHA256=${CRATE_CHECKSUM}
    HTTP_HEADER   "User-Agent: CMake-FetchContent" # crates.io requires a UserAgent to be set
)
EOF
}
```
(The Python call can also be replaced with `grep -o -P '(?<="checksum":")[a-fA-F0-9]+(?=")'`, but then you have to feel bad for using grep to parse JSON)

Example:
```
$ get-rust-crate-url-and-hash libc 0.2.0
FetchContent_Declare(
  libc
  URL "https://crates.io/api/v1/crates/libc/0.2.0/download"
  URL_HASH SHA256=fd386f0746b2a12a14f1256fa1ee9a31c584aadcdd0b72b15a4cb59381e60b2d
  HTTP_HEADER   "User-Agent: CMake-FetchContent" # crates.io requires a UserAgent to be set
)
```

---

EDIT: crates.io has recently started enforcing that you have a UserAgent set when accessing their API. Added `-A` to the curl command and `HTTP_HEADER` to the FetchContent block to make the helper work.
