### ISSUE TITLE
Figure out how to apply global/directory flags to link step

### ISSUE THREAD

**Issue by AndrewGaspar** [corrosion-rs/corrosion#46]
We really aught to apply global and directory flags to the link line in cargo. Examples include, but are not limited to:
- `CMAKE_<lang>_FLAGS`
- `CMAKE_SHARED_LINKER_FLAGS`
- `CMAKE_EXE_LINKER_FLAGS`

We're actually probably kind of broken if we don't do this.

**Comment by AndrewGaspar** [comment]
This might help in CMake 3.19: https://cmake.org/cmake/help/latest/command/cmake_language.html#deferring-calls

We could defer enumerating dependencies until the end of the project directory: `cmake_language(DEFER DIRECTORY ${PROJECT_SOURCE_DIR} ...)`

**Comment by AndrewGaspar** [comment]
Hm... might not work - seems like you can only execute sub commands, not run additional scripts.

**Comment by AndrewGaspar** [comment]
Actually, it seems like `<command>` doesn't mean executable, it means cmake function.

**Comment by jschwe** [comment]
Closing this issue. I think it's fine to put the responsibility on the user to add the correct flags per target.
