### ISSUE TITLE
[Bug]:cross compile failed  

### ISSUE THREAD

**Issue by klaushhp** [corrosion-rs/corrosion#473]
### Current Behavior

To compile to arrch64 version in x86_64 linux. I configured the macro Rust_CARGO_TARGET=aarch64-unknown-linux-gnu. Cmake can varify this target, but it choose the wrong toolchain, it still use the default toolchain(stable-x86_64-unknown-linux-gnu).

### Environment

```markdown
- OS:linux
- CMake:3.21.0
- CMake Generator:
```

### CMake configure log with Debug log-level

-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 6.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/gcc-linaro-6.5.0-2018.12-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Rust Toolchain: stable-x86_64-unknown-linux-gnu
-- Determining required link libraries for target aarch64-unknown-linux-gnu
-- Required static libs for target aarch64-unknown-linux-gnu: gcc_s;util;rt;pthread;m;dl;c
-- Determining required link libraries for target x86_64-unknown-linux-gnu
-- Required static libs for host target x86_64-unknown-linux-gnu: gcc_s;util;rt;pthread;m;dl;c
-- Found Rust: /home/uie97822/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc (found version "1.75.0") 
-- Using Corrosion as a subdirectory
-- Configuring done
-- Generating done
-- Build files have been written to: /home/uie97822/mfc5j3_appsw_adr/Adr/build/build-arm64

### CMake Build step log

cmake -S.. -Bbuild-arm64 -DRust_CARGO_TARGET=aarch64-unknown-linux-gnu -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++

**Comment by jschwe** [comment]
>  but it choose the wrong toolchain, it still use the default toolchain(stable-x86_64-unknown-linux-gnu).

This is correct. Rust is a cross-compiler (same as clang for C). Your host system presumably is Linux on x86_64, so you are using Rust built for running on x86_64. Your build is targeting aarch64, and this can be done with the same compiler, since Rust supports all targets in one toolchain (as opposed to gcc). 

You also haven't posted an actual error - did you experience any other issues when running `cmake --build build-arm64`?
