### ISSUE TITLE
Refactor CI to be multi-stage

### ISSUE THREAD

**Issue by AndrewGaspar** [corrosion-rs/corrosion#48]
Currently we generate a massive matrix of configurations (rust toolchain, cmake version, platform, etc.) and bootstrap all of Corrosion. Really what I should do is just a handful of bootstrap jobs and then run faster tests using the install from those bootstrap tests. There will still be explicit tests for using corrosion as a submodule.

**Comment by jschwe** [comment]
CI now caches the CMake Generator for the legacy Generator. In all other cases there is only CMake so there is nothing much left to be gained.
