### ISSUE TITLE
Breaking change to target names containing dashes with Rust 1.79

### ISSUE THREAD

**Issue by jschwe** [corrosion-rs/corrosion#501]
`cargo-metadata` output for target names changes with Rust 1.79 due to PR https://github.com/rust-lang/cargo/pull/12783 fixing issue https://github.com/rust-lang/cargo/issues/12780. (TLDR: dashes in target names are replaced with underscores starting with Rust 1.79)

Users would notice this by receiving errors that CMake can't find Rust targets with dashes in the name anymore, e.g.:
```
CMake Error at /Users/jschwender/Dev/corrosion/cmake/Corrosion.cmake:1172 (set_property):
  set_property could not find TARGET rustflag-test-lib.  Perhaps it has not
  yet been created.
Call Stack (most recent call first):
  CMakeLists.txt:11 (corrosion_add_target_rustflags)

```

### Example of an affected Cargo.toml file:

```toml
[package]
name = "flags-lib"
version = "0.1.0"
edition = "2018"

[lib]
# Note how there is no explicit `name` field here.
crate-type=["staticlib"]
```

With Rust 1.79, corrosion would now import a crate named `flags_lib`, i.e. the CMake target name changed.

### Affected crates

- Cargo packages which use dashes in their package name AND
- do not specify an explicit name in the `[lib]`  section
- `bin` crates are NOT affected.

### Solution / Required actions

- Corrosion v0.5 and later replace all dashes in imported target names with underscores, to get consistent CMake target names independent of the used Rust version. All users should upgrade from v0.4.x to v0.5.
- You will need to change the target name of rust libraries in your CMake code to use underscores.
- If you are not able to update corrosion, users can assign an explicit name in the `[lib]` or `[[bin]]` sections of their `Cargo.toml` manifests, and use that name in their CMake code. (Note: Cargo already forbids dashes in lib and bin target names). You may refer to https://github.com/slint-ui/slint/commit/eeb7bad4aeec0fcdef16d59f74467cf908c6af13 for an example fix, without updating corrosion.

**Comment by tronical** [comment]
We ran into the same issue but worked around it by explicitly setting lib.name (https://github.com/slint-ui/slint/commit/eeb7bad4aeec0fcdef16d59f74467cf908c6af13 ).

But I guess it also ok to do a _ -> - transformation unconditionally in corrosion.

**Comment by jschwe** [comment]
Corrosion v0.5 and newer unconditionally replace dashes with underscores in library names, to match the behavior of Rust 1.79 and newer.
