### ISSUE TITLE
Cannot use corrosion_experimental_cbindgen with a rlib target

### ISSUE THREAD

**Issue by flaviojs** [corrosion-rs/corrosion#562]
I am converting code from C to rust, placing the converted code into a rlib crate (foo-c).

cmake needs to produce 2 staticlibs of the converted code, for stable and unstable versions of the code.
For that I have 2 staticlib crates that just propagate features and export public symbols (foo-c-stable and foo-c-unstable)

The crates are part of a workspace and imported at the same time with a single `corrosion_import_crate` call:
 * foo-c (rlib)
 * foo-c-stable (staticlib)
 * foo-c-unstable (staticlib)
 * bin-that-only-needs-the-converted-code (bin)

The C code needs to use the generated header of the converted code.
`corrosion_experimental_cbindgen` is used on foo-c but errors in the `get_target_property` line of:
https://github.com/corrosion-rs/corrosion/blob/3db4ffdbe0e54de934f91a981b0e1d0da538408e/cmake/Corrosion.cmake#L1826-L1836
TARGET is required and MANIFEST_DIRECTORY is provided... so I guess the `else()` branch is supposed to create a target?

After the problem is fixed I need to figure out the proper way to make the C code use the generated header, probably by modifying the foo-c-stable and foo-c-unstable targets in some way. Some guidance is welcome. :)

#159 seems related to this

---

**My current workaround:**

The foo-c crate is also a staticlib for the stable code and is used to generate the header.
The foo-c-unstable target has the expected header dir manually added with `target_include_directories(INTERFACE)`.
The foo-c-unstable target manually depends on the internal "bindings" target of the foo-c target. (hack)

I want to use the workspace organization that I described, not this workaround,

**Comment by jschwe** [comment]
If you run cbindgen on the static libs, will cbindgen not generate the bindings if you re-export the public API? 

It doesn't make much sense to me to run cbindgen on an intermediate library, that is not the final artifact, since the final static / shared library determines what it's public API is.

**Comment by flaviojs** [comment]
cbindgen produces a header that works with all feature combinations, foo-c is the right target.

foo-c-stable and foo-c-unstable only exist because corrosion-rs does not allow me produce 2 staticlibs of the same crate with different features. They will be removed when all the C code is converted.

**Comment by flaviojs** [comment]
Adding this to `_generator_add_package_targets` before the "bin" case fixes the issue for me:
```cmake
        # "lib/rlib/dylib" cannot be linked, add an empty target.
        # The target can be used with cbindgen to generate a header.
        elseif("lib" IN_LIST kinds OR "rlib" IN_LIST kinds OR "dylib" IN_LIST kinds)
            string(REPLACE "\-" "_" target_name "${target_name}")

            add_library(${target_name} INTERFACE)
            _corrosion_initialize_properties(${target_name})

            list(APPEND corrosion_targets ${target_name})
            set_property(TARGET "${target_name}" PROPERTY COR_CARGO_PACKAGE_NAME "${package_name}" )
```
and adding this to my cmake file makes the C code have access to the generated header:
```cmake
target_link_libraries( foo_c_stable INTERFACE foo_c )
target_link_libraries( foo_c_unstable INTERFACE foo_c )
```

**Comment by flaviojs** [comment]
> It doesn't make much sense to me to run cbindgen on an intermediate library, that is not the final artifact, since the final static / shared library determines what it's public API is.

I expect most FFI tools or libraries produce stuff during or after compilation.

cbindgen uses a different approach. It generates bindings by parsing the source and crate information. (no compilation)
This makes it compatible with `build.rs` and allows headers that support all feature combinations.
The only problem is the limited number of people that review PRs and merge... fixing stuff takes forever. -.-'

foo-c-stable and foo-c-unstable don't have unique code, so cbinbgen would produce the same result for both.
Once again, they only exist to overcome limitations in corrosion-rs.

**Comment by jschwe** [comment]
> Adding this to _generator_add_package_targets before the "bin" case fixes the issue for me:

I don't think corrosion will support importing `rlib`s before the `rlib` format is stabilized. 

> cbindgen produces a header that works with all feature combinations, foo-c is the right target.

To clarify my concerns: 

Assuming you have a `libA` containing `funcA`, and a dynamic `libB` which links `libA`, but does not re-export or use `funcA`. 
As far as I'm aware, the linker is now free to determine that `funcA` is actually unused / unreachable and remove it, unless the user specified the `--whole-archive` option.

In principle running `cbindgen` from corrosion / cmake also doesn't require corrosion to import the crate. 
Instead of reading target properties, you could also let the user pass the crate manifest path as  a function parameter.

> foo-c-stable and foo-c-unstable don't have unique code, so cbinbgen would produce the same result for both.
> Once again, they only exist to overcome limitations in corrosion-rs.

It sounds like what you really want is the ability to import the same crate multiple times, which could be achieved by allowing the user to choose the imported target name.

**Comment by flaviojs** [comment]
> I don't think corrosion will support importing `rlib`s before the `rlib` format is stabilized.

Sure, apparently rlibs can only be used by invoking `rustc` directly: https://stackoverflow.com/q/50731453

> To clarify my concerns:
> 
> Assuming you have a `libA` containing `funcA`, and a dynamic `libB` which links `libA`, but does not re-export or use `funcA`. As far as I'm aware, the linker is now free to determine that `funcA` is actually unused / unreachable and remove it, unless the user specified the `--whole-archive` option.

Not sure how it relates to my case, removing unused/unreachable binary code is totally fine.
Something like libB is not being produced, only binaries.
You can think of foo-c as the source code or binary blob that can generate all libA combinations, with cbindgen creating the C header that supports all libA combinations.
foo-c-stable and foo-c-unstable would be 2 specific libA combinations (based on cmake options).

> In principle running `cbindgen` from corrosion / cmake also doesn't require corrosion to import the crate. Instead of reading target properties, you could also let the user pass the crate manifest path as a function parameter.

I set MANIFEST_DIRECTORY but it errors because the foo-c target does not exist (TARGET is required).
Line 1836 expects a target with COR_CARGO_PACKAGE_NAME set.

I do not know how to correctly create a target with COR_CARGO_PACKAGE_NAME from MANIFEST_DIRECTORY.
Instead, I tried to create an empty target for the rlib where the other targets are being created to see if it was enough.
I confirmed it was enough. Since my cmake+corrosion kung-fu is too weak to make a PR that creates the target in `corrosion_experimental_cbindgen`, the rest is up to you... >.<

> It sounds like what you really want is the ability to import the same crate multiple times, which could be achieved by allowing the user to choose the imported target name.

That is not the point of this issue but yes, that would be better. It is the same code, but with different features enabled.
The staticlib format does not have something like features (a way to select binary code) so the lib has to be compiled multiple times.

**Comment by flaviojs** [comment]
What a frustrating experience... after stripping what I could from corrosion code, this represents what I want to do:
```cmake
# target foo_c_h (header foo_c.h generated with cbindgen)
if( OFF )
    message( FATAL_ERROR "TODO use corrosion_experimental_cbindgen to generate target foo_c_h" )
else()
    set( target_name foo_c_h )
    set( crate_name "foo-c" )
    set( header_name "foo_c.h" )
    set( work_dir "${CMAKE_SOURCE_DIR}/foo-c" )
    set( generated_dir "${CMAKE_BINARY_DIR}/corrosion_generated/cbindgen/${target_name}" )
    file( MAKE_DIRECTORY "${generated_dir}/include" )
    set( generated_header "${generated_dir}/include/${header_name}" )
    file( MAKE_DIRECTORY "${generated_dir}/depfile" )
    set( generated_depfile "${generated_dir}/depfile/${header_name}.d" )
    add_custom_command(
        OUTPUT "${generated_header}"
        COMMAND "${CMAKE_COMMAND}" -E env
            #TARGET=??? # why is this needed?
            cbindgen
                --output "${generated_header}"
                --crate "${crate_name}"
                --depfile "${generated_depfile}"
        COMMENT "Generate cbindgen bindings for crate ${crate_name} and output header ${generated_header}"
        DEPFILE "${generated_depfile}"
        COMMAND_EXPAND_LISTS
        WORKING_DIRECTORY "${work_dir}"
    )
    add_custom_target( _cbindgen-${target_name}
        DEPENDS "${generated_header}"
        COMMENT "Generate ${generated_header} for ${target_name}"
    )
    add_library( ${target_name} INTERFACE )
    target_include_directories( ${target_name} INTERFACE
        $<BUILD_INTERFACE:${generated_dir}/include>
        $<INSTALL_INTERFACE:include>
    )
    add_dependencies( ${target_name} _cbindgen-${target_name} )
endif()
```

I attached the test project that contains this code so you can try it: [foo.zip](https://github.com/user-attachments/files/17566214/foo.zip)
It includes optional code to showcase how the generated header can handle that.

**Comment by jschwe** [comment]
> Not sure how it relates to my case, removing unused/unreachable binary code is totally fine.
>  Something like libB is not being produced, only binaries.

Thats your specific use-case, but its not a general property, which means it can't be merged into corrosion.

> I do not know how to correctly create a target with COR_CARGO_PACKAGE_NAME from MANIFEST_DIRECTORY.

No target is needed, you can just replace reading a target property with passing the package name in as a parameter to the function.

> after stripping what I could from corrosion code, this represents what I want to do:

I would suggest that you just keep that code in your CMake project as a function. Calling cbindgen doesn't really require corrosion in any way, so if you have a specific usecase that can't be supported in corrosion, forking this function and adapting it to your specific use-case in your project is a very reasonable thing to do.

I'll be closing this issue, since `rlib` support is not something that corrosion will have until the rlib format is stabilized.

**Comment by flaviojs** [comment]
Sure, whatever... sharing specific use cases usually helps, but it was poison in this case. -.-'

Since it seems you are stuck in the `rlib` detail (which I don't care about) I'll try showing the problem one last time:
```cmake
corrosion_experimental_cbindgen( TARGET foo_c_h HEADER_NAME "foo_c.h" )
# (message):  `foo_c_h` is not a target imported by corrosion and `MANIFEST_DIRECTORY` was not provided.
corrosion_experimental_cbindgen( TARGET foo_c_h HEADER_NAME "foo_c.h" MANIFEST_DIRECTORY "${CMAKE_SOURCE_DIR}/foo-c/" )
# (get_target_property):  get_target_property() called with non-existent target "foo_c_h".
```
Calling corrosion_experimental_cbindgen without a target **DOES NOT WORK**.

**Comment by flaviojs** [comment]
This is the minimum workaround for corrosion v0.5, for anyone with a similar problem:
```cmake
add_library(foo_c_h INTERFACE) # FIXME workaround for corrosion_experimental_cbindgen(MANIFEST_DIRECTORY)
set_target_properties(foo_c_h PROPERTIES
   INTERFACE_COR_PACKAGE_MANIFEST_PATH "${CMAKE_SOURCE_DIR}/foo-c/Cargo.toml" # for cbindgen working dir
   INTERFACE_COR_CARGO_PACKAGE_NAME "foo-c" # for cbindgen --crate
)
corrosion_experimental_cbindgen(TARGET foo_c_h HEADER_NAME "foo_c.h") # generates the header at build time

target_link_libraries(your_lib_or_bin foo_c_h) # code can include to the generated header
```

It works for any crate type that cbindgen supports (including rlib, which is my case).
When `MANIFEST_DIRECTORY` starts working with non-existent targets, you should switch to that.
