### ISSUE TITLE
Allow target override per CMake target

### ISSUE THREAD

**Issue by ultimaweapon** [corrosion-rs/corrosion#570]
My use case is I have one crate in a workspace that is an OS kernel that need to compile for a different target (e.g. `x86_64-unknown-none`). The target for the kernel will be depend on the target CPU architecture instead of the target environment. Let's sat I would like to cross-compile the whole project for `aarch64-unknown-linux-gnu` the target for the kernel would be `aarch64-unknown-none-softfloat`. Currently I'm using `add_custom_target` to build the kernel like this:

```cmake
if(WIN32)
    if(${CMAKE_SYSTEM_PROCESSOR} STREQUAL "AMD64")
        set(KERNEL_TARGET x86_64-unknown-none)
    else()
        message(FATAL_ERROR "Target CPU is not supported")
    endif()
else()
    if(${CMAKE_SYSTEM_PROCESSOR} STREQUAL "x86_64")
        set(KERNEL_TARGET x86_64-unknown-none)
    elseif(${CMAKE_SYSTEM_PROCESSOR} STREQUAL "arm64" OR ${CMAKE_SYSTEM_PROCESSOR} STREQUAL "aarch64")
        # Pre-compiled core crate for aarch64-unknown-none-softfloat does not support
        # Position-Independent Executable so we need nightly toolchain for build-std feature to
        # re-build core crate to support Position-Independent Executable.
        set(KERNEL_TARGET aarch64-unknown-none-softfloat)
        set(KERNEL_TOOLCHAIN +nightly)
        set(KERNEL_OPTS -Z build-std=core,alloc)
    else()
        message(FATAL_ERROR "Target CPU is not supported")
    endif()
endif()

set(KERNEL_OUTPUTS $<IF:$<CONFIG:Debug>,${CMAKE_CURRENT_SOURCE_DIR}/target/${KERNEL_TARGET}/debug,${CMAKE_CURRENT_SOURCE_DIR}/target/${KERNEL_TARGET}/release>)
set(KERNEL ${KERNEL_OUTPUTS}/obkrnl)

add_custom_target(kernel
    COMMAND cargo ${KERNEL_TOOLCHAIN} build $<IF:$<CONFIG:Debug>,--profile=dev,--release> --target ${KERNEL_TARGET} ${KERNEL_OPTS}
    WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/kernel
    BYPRODUCTS ${KERNEL})
```

It would be great if I can use Corrosion to build instead.

**Comment by jschwe** [comment]
CMake doesn't support targeting multiple platforms / targets at the same time. Corrosion relies on some target specific information from CMake, such as the configured c/c++ compiler.

Corrosion does already have  some logic to allow building selected rust executables for the host platform, even when cmake is configured for cross-compiling, however that already has a high complexity and broken corner cases. Extending this to arbitrary target compiler overrides is not feasible in my opinion.

the common way to solve this issue in cmake is to use an approach [like in this stackoverflow answer](https://stackoverflow.com/questions/56435426/how-can-i-use-multiple-toolchains-in-a-cmake-buildsystem-configuration), i.e. using cmake to drive another inner cmake configuration for a different target platform.
