### ISSUE TITLE
Dev warning when the stable-i686-unknown-linux-gnu toolchain is installed

### ISSUE THREAD

**Issue by flaviojs** [corrosion-rs/corrosion#571]
I'm using the toolchain `stable-x86_64-unknown-linux-gnu`.
Using rustup I installed `stable-i686-unknown-linux-gnu` alongside it to try to compile for x86 and started getting this:
```
CMake Warning (dev) at build/_deps/corrosion-src/cmake/FindRust.cmake:363 (message):
  Unexpected output from `rustc --version` for Toolchain
  `stable-i686-unknown-linux-gnu`: ``.

  Ignoring this toolchain.
Call Stack (most recent call first):
  build/_deps/corrosion-src/cmake/Corrosion.cmake:63 (find_package)
  build/_deps/corrosion-src/CMakeLists.txt:73 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.
```
Not sure why but the toolchain does not have a rustc executable.

**Comment by jschwe** [comment]
Is that a corrupt tool chain download, or does it really not have a rustc compiler? How does that work?

**Comment by flaviojs** [comment]
I am able to compile with it, maybe it's a "--target" only toolchain?

You follow https://stackoverflow.com/a/53496910 and test it.

**Comment by jschwe** [comment]
>  Using rustup I installed stable-i686-unknown-linux-gnu alongside it to try to compile for x86 and started getting this:

Did you install a cross-compile target for the host rustup toolchain (i.e. `rustup target install ....`, or did you install another toolchain (i.e. `rustup toolchain install ...`?
How are you configuring corrosion / cmake?

**Comment by flaviojs** [comment]
I don't actually remember how it was initially installed.
I just searched how to compile 32-bit and tried following the web page/pages.
Another project (that I was working on in parallel) that uses cmake+corrosion-rs starting giving the error.

I'm not familiar with rust toolchains or cross-compiling to be able to debug this.
This is my current state according to rustup:
```
$ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/user/.rustup

installed toolchains
--------------------

stable-i686-unknown-linux-gnu
stable-x86_64-unknown-linux-gnu (default)

installed targets for active toolchain
--------------------------------------

i686-unknown-linux-gnu
powerpc-unknown-linux-gnu
x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.82.0 (f6e511eec 2024-10-15)

```

**Comment by jschwe** [comment]
You should use the host rust toolchain and setup corrosion to cross-compile. 
I.e. configure cmake like
```
cmake -S. -Bbuild -DRust_CARGO_TARGET=i686-unknown-linux-gnu -DCMAKE_C_COMPILER=cross-c-compiler other_options
```

This works without any problems.

What you did is probably run the following command which gives a bunch of warnings:
```
rustup toolchain add stable-i686-unknown-linux-gnu
error: DEPRECATED: future versions of rustup will require --force-non-host to install a non-host toolchain.
warning: toolchain 'stable-i686-unknown-linux-gnu' may not be able to run on this system.
warning: If you meant to build software to target that platform, perhaps try `rustup target add i686-unknown-linux-gnu` instead?
```

when trying to use this toolchain, I get an error
```
rustc +stable-i686-unknown-linux-gnu --version
error: command failed: 'rustc': No such file or directory (os error 2)
```

Thats not a corrosion issue, but an upstream issue (which is only relevant if you really need a 32-bit compiler, e.g. because you are compiling **on** a 32-bit machine.

**Comment by flaviojs** [comment]
Thanks, that works.

Can you improve the error message so it points users to the right direction?
Something like:
```cmake
                message(AUTHOR_WARNING "Unexpected output from `rustc --version` for Toolchain `${_TOOLCHAIN}`: "
                        "`${_TOOLCHAIN_RAW_VERSION}`.\n"
                        "Ignoring this toolchain.\n"
                        "If this is not your native toolchain you should remove it with `rustup toolchain uninstall ${_TOOLCHAIN}` and add a target to your native toolchain."
                )
```
