### ISSUE TITLE
Is it not possible to tell corrosion to use pre-fetched crates and NOT attempt to download?

### ISSUE THREAD

**Issue by jrmarino** [corrosion-rs/corrosion#578]
for example:
```
# Import taskchampion-lib as a CMake library. This implements the Rust side of
# the cxxbridge, and depends on the `taskchampion` crate.
corrosion_import_crate(
  MANIFEST_PATH "${CMAKE_SOURCE_DIR}/Cargo.toml"
  LOCKED
  CRATES "taskchampion-lib"
  FEATURES "${TASKCHAMPION_FEATURES}")

# Set up `taskchampion-cpp`, the C++ side of the bridge.
corrosion_add_cxxbridge(taskchampion-cpp
  CRATE taskchampion_lib
  FILES lib.rs
)
```
In this sandbox, internet connectivity is intentionally disabled, so the crates have been prefetched and placed at /myloc/cargo-crates.
I haven't been able to figure out how to tell corrosion_import_crate this location (so downloading isn't required).

This is an example of how I typically do this with cargo directly:
```
        # create directives
        ${MKDIR} ${WRKSRC}/.cargo
        echo "[source.cargo]" >> ${WRKSRC}/.cargo/config.toml
        echo "directory = '${CARGO_VENDOR_DIR}'" >> ${WRKSRC}/.cargo/config.toml
        echo "[source.crates-io]" >> ${WRKSRC}/.cargo/config.toml
        echo "replace-with = 'cargo'" >> ${WRKSRC}/.cargo/config.toml
```

So is it possible to use corrosion offline with prepositioned crates?

**Comment by jschwe** [comment]
Adding a .cargo/config.toml should work. Under the hood corrosion just calls cargo. There is no mechanism in corrosion to generate a config.toml, but you could do that in your own cmake code if you wanted. 
Let me know if you run into any issues with that. 
I think you may also need to pass some additional cargo flags to cargo via corrosion, (perhaps it was --frozen ) to avoid cargo metadata accessing the Internet.

**Comment by jschwe** [comment]
This was also discussed in https://github.com/GothenburgBitFactory/taskwarrior/issues/3705 and using cargo vendor + installing the correct version of `cxxbridge` in advance seems to work fine for them.

I opened https://github.com/corrosion-rs/corrosion/issues/588 to track potential improvements to corrosion to allow installing cxxbridge / cbindgen from vendored sources.

**Comment by jrmarino** [comment]
I built cxxbridge separately (which was not easy) and set INSTALLED_CXXBRIDGE in cmake, but now taskwarrior is complaining about cxx being missing.  Now I'm not sure if cxxbridge + cxx versions have to be exactly what's bundled with taskwarrior releases.

I've literally spent hours and hours on this - If taskwarrior can't be easily maintained with offline sources, it might be time to just drop it.  I can see from the links that issues opened on this is closed so I'm guessing nothing is going to change any time some.

sorry.  the maintenance on this for source-building repos is so heavy starting with version 3.2.0
