### ISSUE TITLE
Loose version check of `cxxbridge` executable?

### ISSUE THREAD

**Issue by doronbehar** [corrosion-rs/corrosion#582]
Hello,

I'm not using this package directly, but I came here after experiencing several issues with Taskwarrior, which uses this crate. The details are available here:

- https://github.com/GothenburgBitFactory/taskwarrior/issues/3705

Anyway, we noticed you write this:

https://github.com/corrosion-rs/corrosion/blob/b816285a706acbf3efa8a946f834ca32e093ff41/cmake/Corrosion.cmake#L1548

But the truth is:

https://github.com/corrosion-rs/corrosion/blob/b816285a706acbf3efa8a946f834ca32e093ff41/cmake/Corrosion.cmake#L1613

**Comment by jschwe** [comment]
The CMake documentation for [find_program](https://cmake.org/cmake/help/latest/command/find_program.html) states

> `HINTS`, `PATHS`
>
 >   Specify directories to search **in addition to the default locations**. The ENV var sub-option reads paths from a system environment variable.

(Emphasis mine)

**Comment by doronbehar** [comment]
OK thanks, I just realized that it is probably the strict version check of `cxxbridge` that made your cmake rules appear as "not found", because the version our distribution provides doesn't match the one found in the `Cargo.lock` file of `taskwarrior`...

I wonder, why did you use such a strict version check? Did you get convinced that patch/minor version bumps of `cxxbridge` can be very incompatible with previous ones? It is supposed to be stable ever since it reached version `1.0.0`.. Perhaps you'd be able to slightly loose that version check? [`cxx` releases new version roughly every few weeks](https://github.com/dtolnay/cxx/releases/), and it is hard for us distributors to keep the versions of our distributed `cxxbridge` and the `cxx` version specified in `Cargo.lock` files of packages that depend on `cxxbridge`...

**Comment by jschwe** [comment]
My conservative assumption is that cxxbridge and the cxx macros are tightly coupled. Is there any official documentation that indicates otherwise? Perhaps it would be worth opening an issue over at the cxx project and asking if cxxbridge and the cxx macros need to be the same version or if there is some level of compatibility across versions.

**Comment by doronbehar** [comment]
OK I asked them:

- https://github.com/dtolnay/cxx/issues/1407

**Comment by jschwe** [comment]
Given that the official answer is that cxxbridge must be the same version as cxx, I'll be closing this issue.
