### ISSUE TITLE
Quiet flag is not that quiet

### ISSUE THREAD

**Issue by xTachyon** [corrosion-rs/corrosion#583]
I'm passing `FLAGS -q` to my build. Unfortunately, using the ninja generator, this still prints the commands it is running to the terminal, and it doesn't erase them like normal.

As far as I can tell, the problem is [USES_TERMINAL](https://github.com/corrosion-rs/corrosion/blob/4628b4d9df405cc55ac135a073900373c877d829/cmake/Corrosion.cmake#L795) (both of them). I *think* I understand why it's passed and it makes sense, but for my case it's not helpful. I just commented it out in my build.

What I'm looking for is a proper solution for this: maybe an option in `corrosion_import_crate` that either passes `-q` and no `USES_TERMINAL`, or at least something that disables `USES_TERMINAL`.

What do you think?

**Comment by jschwe** [comment]
`FLAGS -q` just passes the `-q` flag to cargo. As I'm understanding, you are not seeing any output from cargo right?
Is passing a `-q` flag to Ninja an option, or does this silence too much?

**Comment by xTachyon** [comment]
I am not seeing output from cargo, which is what I want. Passing `--quiet` to ninja is too much.

My problem is that because those commands are under `pool = console`, their respective lines when ninja prints will not go away like a normal command.

**Comment by xTachyon** [comment]
On a test project:
![Screenshot_20241211_102145](https://github.com/user-attachments/assets/a07cfff0-a8e4-4b1e-be0f-87184dfdc390)

In the first ninja run, `USES_TERMINAL` is activated, and in the second ninja run, it is not.
Notice how in the first run there's an extra line `[0/4] cd ...`.

For a real project I have many similar lines, which is quite unnecessary and annoying.

**Comment by jschwe** [comment]
I think the `USES_TERMINAL` is mainly to allow colored output to the terminal by cargo. Probably that is something we want to keep as a default. But I wouldn't mind if we add a flag which allows disabling USES_TERMINAL.

**Comment by xTachyon** [comment]
A flag to disable it sounds good.
