### ISSUE TITLE
Specify that imported crates should build for HOST

### ISSUE THREAD

**Issue by AndrewGaspar** [corrosion-rs/corrosion#62]
This is specifically for "build tools" - basically, if you're cross-compiling, you still want your build tools to build for the host architecture. Similarly to cargo build scripts, this will probably mean just not using the `--target` flag, which generally gives the correct result for the host architecture - should be the same as the toolchain architecture.

Considerations: Potentially not allowing you to call `corrosion_link_libraries` on these imported crates? Or only for libraries that aren't CMake targets, perhaps? I don't know, need to consider this more.

**Comment by jschwe** [comment]
Corrosion supports marking a target as ´hostbuild´, so I think this issue is already resolved.
