### ISSUE TITLE
Output crate artifacts to standard locations

### ISSUE THREAD

**Issue by AndrewGaspar** [corrosion-rs/corrosion#65]
RE: https://github.com/AndrewGaspar/corrosion/issues/60#issuecomment-705529748

Currently bins and libs are just left in the cargo build tree, which is out of sync with where CMake-native artifacts are placed. Artifacts should be placed in CMAKE_CURRENT_BINARY_DIR. Placement should also respect "OUTPUT_DIRECTORY" properties:
- [ARCHIVE_OUTPUT_DIRECTORY](https://cmake.org/cmake/help/latest/prop_tgt/ARCHIVE_OUTPUT_DIRECTORY.html)
- [LIBRARY_OUTPUT_DIRECTORY](https://cmake.org/cmake/help/latest/prop_tgt/LIBRARY_OUTPUT_DIRECTORY.html)
- [RUNTIME_OUTPUT_DIRECTORY](https://cmake.org/cmake/help/latest/prop_tgt/RUNTIME_OUTPUT_DIRECTORY.html)
- [PDB_OUTPUT_DIRECTORY](https://cmake.org/cmake/help/latest/prop_tgt/PDB_OUTPUT_DIRECTORY.html)
- [COMPILE_PDB_OUTPUT_DIRECTORY](https://cmake.org/cmake/help/latest/prop_tgt/COMPILE_PDB_OUTPUT_DIRECTORY.html)

**Comment by kjeremy** [comment]
I could try to tackle this with some guidance if it's relatively straightforward.

**Comment by AndrewGaspar** [comment]
Roughly, you'll need to do some updates to [`_add_cargo_build`](https://github.com/AndrewGaspar/corrosion/blob/bf3af38e4f404525af92c381fe81394617b67087/cmake/Corrosion.cmake#L64)

- You'll need to add a `${CMAKE_COMMAND} -E copy` call in the `add_custom_target` call towards the end of the function to move the build artifacts to the target location from the cargo build tree - by default I _think_ this would be ${CMAKE_CURRENT_BINARY_DIR} for all target types
- You'll need to use the overloaded target output directories (listed above) if they're set in place of CMAKE_CURRENT_BINARY_DIR
  - This has a rub - normally you'd want to use generator expressions to make sure if the user changes those target properties _after_ they import the crate, the property is still respected. Unfortunately, the `BYPRODUCTS` portion of `add_custom_target` doesn't support generator expressions, and setting `BYPRODUCTS` is necessary for using the Ninja generator. You can either just use `get_target_property` in all cases, with the downside that you won't be able to use `set_target_property` to set the property, or use `get_target_property` when using the Ninja generator and generator expressions for all other generators. I probably prefer the former option so that the behavior is uniform no matter what generator you're using. There's some existing discussion of this issue here: https://github.com/AndrewGaspar/corrosion/issues/50
- You'll need to update the `byproducts` variable to point to the new build location - this should be fairly easy in the default case, since `BYPRODUCTS` is relative to CMAKE_CURRENT_BINARY_DIR by default, but you'll also need to implement it when using the custom locations

We currently don't track the pdb files at all, but those should be fairly easy to implement - should be output in the same place as all the other artifacts. However, if you're not on a Windows machine, then don't worry about it - I can add support for copying those later.

**Comment by kjeremy** [comment]
I can't figure out how to get the TYPE of each target in cmake. It always reports `UTILITY`. My current thinking is that we would need to pass it as an argument to `_add_cargo_build` since it's known here: https://github.com/AndrewGaspar/corrosion/blob/master/generator/src/subcommands/gen_cmake/target.rs#L109-L129
