### ISSUE TITLE
Apply OPTIMIZE_DEPENDENCIES to Rust static libraries on CMake 3.19+

### ISSUE THREAD

**Issue by AndrewGaspar** [corrosion-rs/corrosion#71]
If a Rust static library depends on native static libraries, it doesn't need to wait for those native static libraries to be built before the crate is built. Therefore, we can safely apply [`OPTIMIZE_DEPENDENCIES`](https://cmake.org/cmake/help/latest/prop_tgt/OPTIMIZE_DEPENDENCIES.html#prop_tgt:OPTIMIZE_DEPENDENCIES). Available only on CMake 3.19+.

**Comment by AndrewGaspar** [comment]
Note that this won't help with Ninja generators at all - only generators which don't support `BYPRODUCTS`.

**Comment by jschwe** [comment]
I'm not sure if this makes any sense for imported libraries. The imported rust static library only has the `cargo_build_xxx` target as a dependency, and that can't be optimized anyway. I also don't see any other situations where the user would want to add additional dependencies on this static library.

I'm going to close this issue for now, but if someone ever discovers a concrete usecase, feel free to comment / reopen.
