### ISSUE TITLE
Use gcc -dumpmachine to automatically derive Rust_CARGO_TARGET

### ISSUE THREAD

**Issue by AndrewGaspar** [corrosion-rs/corrosion#72]
`gcc -dumpmachine` allows you to get the target triple of the selected compiler, so it should be possible to do a reasonable job of deriving an appropriate cargo target triple from this.

Some info here: https://wiki.osdev.org/Target_Triplet

**Comment by AndrewGaspar** [comment]
Should only apply when `CMAKE_CXX_COMPILER_ID STREQUAL "GNU"`

**Comment by jschwe** [comment]
gcc target triples and clang target triples don't always match 1:1 as far as I know, so I don't think this is worth the effort.
