### ISSUE TITLE
Provide environment variables to learn about CMake properties

### ISSUE THREAD

**Issue by humenda** [corrosion-rs/corrosion#80]
For the development of procedural macros that interact with the C world, it would be great to expose some of the CMake variables using environment variables. Most prominent would be the build directory. There is already `CMAKECARGO_BUILD_DIR`, but that's only exposed to the CMake config generator, not to the `cargo build` invocation.

**Comment by humenda** [comment]
An alternative would be to allow custom variables to be passed to `corrosion_import_crate`. I would imagine a keyword argument that can occur 0-n times and that allows information such as the build directory, but also any other CMake information to be passed.

**Comment by AndrewGaspar** [comment]
> An alternative would be to allow custom variables to be passed to corrosion_import_crate. I would imagine a keyword argument that can occur 0-n times and that allows information such as the build directory, but also any other CMake information to be passed.

I've actually thought about doing this in the past. For example, let's say you were using Corrosion and an `*-sys` crate in Rust - it would be useful to be able to tell that crate to find libraries, etc. at the same place that CMake found the library.

**Comment by AndrewGaspar** [comment]
I think the [`cmake-file-api`](https://cmake.org/cmake/help/latest/manual/cmake-file-api.7.html#v1-client-stateful-query-files) would be helpful here, too.

**Comment by neachdainn** [comment]
> For example, let's say you were using Corrosion and an *-sys crate in Rust - it would be useful to be able to tell that crate to find libraries, etc. at the same place that CMake found the library.

That is doable right now, if a little painful:

```cmake
find_package(foo REQUIRED)
list(TRANSFORM foo_LIBRARIES PREPEND "-L" OUTPUT_VARIABLE RUSTFLAGS)
string(REPLACE ";" " " RUSTFLAGS "${RUSTFLAGS}")
set(ENV{RUSTFLAGS} "${RUSTFLAGS}")
```

After that, you do *not* do any linking inside of Rust. I.e., do *not* have a `#[link(name = "foo")]`.

**Comment by neachdainn** [comment]
I should have double checked before I commented:  something is happening during the build to make the linker not respect `RUSTFLAGS`. Running Cargo directly with the Rust flags (e.g., `RUSTFLAGS="-l/path/to/libfoo.so" cargo run`) works, and passing invalid flags via CMake (e.g., `set(ENV{RUSTFLAGS} "-WAAAGH")`) does cause Cargo to fail, but something is happening during linking that I didn't expect.

**Comment by neachdainn** [comment]
[Found it][1]

[1]

**Comment by AndrewGaspar** [comment]
> Does Corrosion link manually?

No, but it does specify the linker to use, prioritizing the compiler for the language of highest precedence that it links. (e.g. if you link a C++ library, it will tell cargo to link using the C++ compiler). This is done to ensure the correct standard libraries are linked against.

I actually wish there was some way to rip linking completely out of cargo's hands - build all the objects using cargo, but then do the final link step, including for ELFs (executables and .so's), via CMake's default mechanisms. Would make certain things a lot easier... Unfortunately 1) there's no way to tell cargo to not perform the final link step, I don't think, and 2) Corrosion would then need to be able to discover all the objects and libraries and link options that Cargo wants to specify.

So instead, I think for now I need to go the other way and just try to tell Cargo as much as possible to specify to the link options. Unfortunately, this is a bit of a bifurcation between static Rust libraries and shared Rust libraries/executables. For the former, the final link step is handled entirely in CMake, which makes some things easier, but in the latter, it's handled entirely in Cargo.

**Comment by neachdainn** [comment]
I'm going to stop commenting here because I think trying to fix my non-optimal solution isn't really addressing this issue (or the optimal solution). I'll comment on the pull request.

**Comment by humenda** [comment]
Is it possible to write the query file during the configure stage to
`CMAKE_BINARY_DIR` and have it picked up by CMake? Or does it need to be in
the build directory strictly before configuring CMake?

**Comment by AndrewGaspar** [comment]
> s it possible to write the query file during the configure stage to `CMAKE_BINARY_DIR` and have it picked up by CMake? 

Yes, you can, which should be sufficient because you can request it to just output the entire build graph using "codemodel", which raises the question - why doesn't CMake always output it? 🙃 I've also experimented with just re-configuring during the build stage, which is undesirable because it might break with poorly designed CMake files that don't cache their inputs, but it "works".

One downside of the file API is that it doesn't output the imported targets. However, it _does_ output all the flags, includes, libs, etc. for concrete targets. I wonder if I could just create dummy libraries for each Rust target, which would then get me the full list-out of imported flags, libs, and includes.

**Comment by humenda** [comment]
Ok, I checked the documentation in more detail. The API might provide a lot of
useful information, but the particular one I'm interested is missing: the
build directory. Without it, I can only hardcode "build" into the build.rs
that I'm using. Maybe at least this one could be passed by Corrosion to Cargo
as an environment variable?

**Comment by jschwe** [comment]
> For the development of procedural macros that interact with the C world, it would be great to expose some of the CMake variables using environment variables. Most prominent would be the build directory. There is already CMAKECARGO_BUILD_DIR, but that's only exposed to the CMake config generator, not to the cargo build invocation.

@humenda Now that you can pass arbitrary variables via the `CORROSION_ENVIRONMENT_VARIABLES` target property, I think this issue can be closed. Feel free to reopen, if there is still something you are missing.

**Comment by humenda** [comment]
>> For the development of procedural macros that interact with the C world, it would be great to expose some of the CMake variables using environment variables. Most prominent would be the build directory. There is already CMAKECARGO_BUILD_DIR, but that's only exposed to the CMake config generator, not to the cargo build invocation.
>
***@***.*** Now that you can pass arbitrary variables via the `CORROSION_ENVIRONMENT_VARIABLES` target property

Thanks, I didn't follow this closely. Looks exactly like requested ;).
