### ISSUE TITLE
CorrosionConfig.cmake looks in wrong place for Corrosion::Generator when CMAKE_INSTALL_LIBEXEC is an absolute path

### ISSUE THREAD

**Issue by surprized** [corrosion-rs/corrosion#84]
When packaging for openSUSE, we use the RPM macro ```%cmake``` to set default install directories, so that the command expands to:
```/usr/bin/cmake /home/abuild/rpmbuild/BUILD/corrosion-git.20201129.2e4c62c/. '-GUnix Makefiles' -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DCMAKE_INSTALL_LIBDIR:PATH=lib64 -DCMAKE_INSTALL_LIBEXECDIR=/usr/libexec -DCMAKE_BUILD_TYPE=RelWithDebInfo '-DCMAKE_C_FLAGS=-mbranch-protection=standard -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -DNDEBUG' '-DCMAKE_CXX_FLAGS=-mbranch-protection=standard -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -DNDEBUG' '-DCMAKE_Fortran_FLAGS=-mbranch-protection=standard -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -DNDEBUG' '-DCMAKE_EXE_LINKER_FLAGS=-flto=auto -Wl,--as-needed -Wl,--no-undefined -Wl,-z,now' '-DCMAKE_MODULE_LINKER_FLAGS=-flto=auto -Wl,--as-needed' '-DCMAKE_SHARED_LINKER_FLAGS=-flto=auto -Wl,--as-needed -Wl,--no-undefined -Wl,-z,now' -DLIB_SUFFIX=64 -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON -DBUILD_STATIC_LIBS:BOOL=OFF -DCMAKE_COLOR_MAKEFILE:BOOL=OFF -DCMAKE_INSTALL_DO_STRIP:BOOL=OFF -DCMAKE_MODULES_INSTALL_DIR=/usr/lib64/cmake/corrosion```
Builds with no problems, but when actually using it on a program it gives the following error:
```[...]
[   87s] -- Rust Target: aarch64-unknown-linux-gnu
[   87s] -- Found Rust: /usr/bin/rustc (found version "1.47.0") 
[   87s] No such file or directory
[   87s] CMake Error at /usr/share/cmake/Corrosion.cmake:235 (message):
[   87s]   corrosion-generator failed: 1
[   87s] Call Stack (most recent call first):
[   87s]   src/CMakeLists.txt:28 (corrosion_import_crate)
```
Seems to be along the lines of #52 and #75.
When Corrosion is installed to /usr/local/ (just using plain CMake without options) it does "run" properly.

**Comment by AndrewGaspar** [comment]
Hm... I'll try to look into this. It's not immediately obvious what's happening since everything seems to be in the correct relate path per your specification. It's possible we aren't respect some of those `INSTALL_DIR` variables?

**Comment by surprized** [comment]
This is the generated tree when installing 'normally':
```
usr
├── local
│   ├── lib64
│   │   └── cmake
│   │       └── Corrosion
│   │           ├── CorrosionConfig.cmake
│   │           └── CorrosionConfigVersion.cmake
│   ├── libexec
│   │   └── corrosion-generator
│   └── share
│       └── cmake
│           ├── Corrosion.cmake
│           └── FindRust.cmake
└── share
    ├── doc
    │   └── packages
    │       └── corrosion
    │           └── README.md
    └── licenses
        └── corrosion
            └── LICENSE
```
This is the tree with the packaging flags:
```
usr
├── lib64
│   └── cmake
│       └── Corrosion
│           ├── CorrosionConfig.cmake
│           └── CorrosionConfigVersion.cmake
├── libexec
│   └── corrosion-generator
└── share
    ├── cmake
    │   ├── Corrosion.cmake
    │   └── FindRust.cmake
    ├── doc
    │   └── packages
    │       └── corrosion
    │           └── README.md
    └── licenses
        └── corrosion
            └── LICENSE
```

**Comment by AndrewGaspar** [comment]
Oh, I think I know what it is - this looks sus: https://github.com/AndrewGaspar/corrosion/blob/master/cmake/CorrosionConfig.cmake.in#L12

I had assumed that `CMAKE_INSTALL_LIBEXECDIR` was a directory relative to the install prefix, but in your case it's a full path. I *could* just always use `CMAKE_INSTALL_FULL_LIBEXECDIR`, but that makes the package non-relocatable, which kind of stinks (I'd like to have pre-built releases at some point).

I'll figure something out.

**Comment by AndrewGaspar** [comment]
Out of curiosity, what is leading you to create an OpenSUSE package for corrosion? I'd love to know how people are using Corrosion in the wild.

**Comment by surprized** [comment]
It is a soft dependency of [Angelfish](https://invent.kde.org/plasma-mobile/plasma-angelfish), the Plasma Mobile web browser.
[Provides the adblock functionality](https://invent.kde.org/plasma-mobile/plasma-angelfish/-/merge_requests/97).

**Comment by bhush9** [comment]
@AndrewGaspar : see also

https://jbbgameich.github.io/misc/2020/12/21/rust-in-a-kde-project.html

https://carlschwan.eu/2021/01/20/efficient-custom-shapes-in-qtquick-with-rust/

**Comment by dotlambda** [comment]
Any updates on this? I ran into the same issue while packaging angelfish for NixOS.

**Comment by AndrewGaspar** [comment]
Yeah, I actually have a fix for this and was stuck on adding testing. I'll get the fix merged in and add testing later.

**Comment by AndrewGaspar** [comment]
I'll try to look into it - haven't had much time to work on Corrosion lately. 😔
