### ISSUE TITLE
Map CMake compilers to cargo build environment variables

### ISSUE THREAD

**Issue by Chaz6** [corrosion-rs/corrosion#85]
I tried to compile a project that failed because it used `c++` instead of the compiler specified in `CMAKE_CXX_COMPILER` (for example, `clang++`). I temporarly fixed this by making a link to `clang++` from `c++` in a location searched by $PATH before /usr/bin, but I think the better solution would be for corrosion to use the compiler specified by CMAKE_CXX_COMPILER.

**Comment by AndrewGaspar** [comment]
Was this in the context of a build script in Cargo? This is something I've wanted to fix at some point - basically, when invoking cargo, set `CC`, `CXX`, etc. to the compilers selected by CMake.

**Comment by Chaz6** [comment]
The project I was trying to build is https://invent.kde.org/graphics/pikasso/ and I am afraid I am not a rust expert, but I enjoy experimenting with new things! I could not find a Cargo.toml but the CMakeLists.txt contains this:-

```
find_package(Corrosion)
set_package_properties(Corrosion PROPERTIES
    PURPOSE "Required for transforming the paths to vertices and indices"
    DESCRIPTION "CMake scripts to seamlessly build and link to targets using cargo"
    URL https://github.com/AndrewGaspar/corrosion
)
```

**Comment by AndrewGaspar** [comment]
Yeah, looks like the case then - this is a known issue. Thank you for filing this!

As a work around, you should also be able to set `CXX=clang++` and get the same behavior, I think.

**Comment by surprized** [comment]
Not sure what is going wrong here, but I [packaged PIkasso](https://build.opensuse.org/package/show/home:andresbs:plasma-mobile/pikasso) without modiying anything, except I exported some rustc flags.
The current gcc bundled in Tumbleweed is gcc-10 IIRC.

**Comment by AndrewGaspar** [comment]
This issue only comes up if you're trying to use a compiler that is not your "default" system compiler (i.e. mapped to `cc`/`c++`, or set via the `CC`/`CXX` environment variables). What's happening is that CMake and the Cargo `cc` crate disagree on which C++ compiler to use because @Chaz6 explicitly set the C++ compiler to use via `CMAKE_CXX_COMPILER`.
